export const FETCH_WEATHER_PENDING = 'FETCH_WEATHER_PENDING';
export const FETCH_CURRENT_SUCESS = 'FETCH_CURRENT_SUCESS';
export const FETCH_FORECAST_SUCESS = 'FETCH_FORECAST_SUCESS';
export const FETCH_WEATHER_ERROR = 'FETCH_WEATHER_ERROR';
export const FETCH_CITY = 'FETCH_CITY';
